<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'WooRefill\\Symfony\\Polyfill\\Php70\\' => array($vendorDir . '/symfony/polyfill-php70'),
    'WooRefill\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'WooRefill\\Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'WooRefill\\Symfony\\Component\\PropertyAccess\\' => array($vendorDir . '/symfony/property-access'),
    'WooRefill\\Symfony\\Component\\OptionsResolver\\' => array($vendorDir . '/symfony/options-resolver'),
    'WooRefill\\Symfony\\Component\\Intl\\' => array($vendorDir . '/symfony/intl'),
    'WooRefill\\Symfony\\Component\\Inflector\\' => array($vendorDir . '/symfony/inflector'),
    'WooRefill\\Symfony\\Component\\HttpFoundation\\' => array($vendorDir . '/symfony/http-foundation'),
    'WooRefill\\Symfony\\Component\\Form\\' => array($vendorDir . '/symfony/form'),
    'WooRefill\\Symfony\\Component\\Filesystem\\' => array($vendorDir . '/symfony/filesystem'),
    'WooRefill\\Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
    'WooRefill\\Symfony\\Component\\DependencyInjection\\' => array($vendorDir . '/symfony/dependency-injection'),
    'WooRefill\\Symfony\\Component\\Config\\' => array($vendorDir . '/symfony/config'),
    'WooRefill\\Symfony\\Bridge\\Twig\\' => array($vendorDir . '/symfony/twig-bridge'),
    'WooRefill\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'WooRefill\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'WooRefill\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'WooRefill\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'WooRefill\\' => array($baseDir . '/src'),
);
