<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Pimple' => array($vendorDir . '/pimple/pimple/src'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src'),
);
